# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742
print("the diameter of {} is {} kilometers.".format(planet,diameter))


the diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
import numpy as np
array=np.zeros(10)
print("an array of 10 zeros:")
print(array)

an array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
import numpy as np
array=np.ones(10)*5
print("an array of 10 zeros:")
print(array)

an array of 10 zeros:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [14]:
import numpy as np
array=np.arange(20,36,2)
print("array of all the even integers from 20 to 35")
print(array)

array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
import numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack((a,b))



array([[1, 2, 3],
       [4, 5, 6]])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [26]:
import pandas as pd

data={'name':['rojer','ram','shiva'],
      'marks':[98,95,90]}
new = pd.DataFrame.from_dict(data)

In [27]:
new

name  marks
0  rojer     98
1    ram     95
2  shiva     90

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [28]:
import datetime
start_date=datetime.date(2023,1,1)
end_date = datetime.date(2023,2,10)
delta=datetime.timedelta(days=1)
while(start_date<= end_date):
  print(start_date,end="\n")
  start_date+= delta

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [30]:
import pandas as pd

list={'s.no':["1","2","3"],
      'name':["a","b","c"],
      'age':[22,23,21]}
  
new=pd.DataFrame(list)

new

s.no name  age
0    1    a   22
1    2    b   23
2    3    c   21